"""add_user_avatar_and_event_images

Revision ID: 49263eb7cb0b
Revises: 589114225e39
Create Date: 2026-04-22 16:52:13.874700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49263eb7cb0b'
down_revision: Union[str, None] = '589114225e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_images',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_images_event_id'), 'event_images', ['event_id'], unique=False)
    op.add_column('users', sa.Column('avatar', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_index(op.f('ix_event_images_event_id'), table_name='event_images')
    op.drop_table('event_images')
    # ### end Alembic commands ###
