"""master grid: event grid dims, seat event_id, nullable zone

Revision ID: 589114225e39
Revises: b22a70f9426c
Create Date: 2026-04-18 10:47:38.743836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '589114225e39'
down_revision: Union[str, None] = 'b22a70f9426c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('grid_rows', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('grid_cols', sa.Integer(), nullable=False))
    op.add_column('seats', sa.Column('event_id', sa.Uuid(), nullable=False))
    op.alter_column('seats', 'zone_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_seat_position'), 'seats', type_='unique')
    op.create_unique_constraint('uq_seat_position', 'seats', ['event_id', 'row_number', 'seat_number'])
    op.create_index(op.f('ix_seats_event_id'), 'seats', ['event_id'], unique=False)
    op.drop_constraint(op.f('seats_zone_id_fkey'), 'seats', type_='foreignkey')
    op.create_foreign_key(None, 'seats', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'seats', 'zones', ['zone_id'], ['id'], ondelete='SET NULL')
    op.alter_column('zones', 'total_rows',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('zones', 'seats_per_row',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zones', 'seats_per_row',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('zones', 'total_rows',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'seats', type_='foreignkey')
    op.drop_constraint(None, 'seats', type_='foreignkey')
    op.create_foreign_key(op.f('seats_zone_id_fkey'), 'seats', 'zones', ['zone_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_seats_event_id'), table_name='seats')
    op.drop_constraint('uq_seat_position', 'seats', type_='unique')
    op.create_unique_constraint(op.f('uq_seat_position'), 'seats', ['zone_id', 'row_number', 'seat_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('seats', 'zone_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('seats', 'event_id')
    op.drop_column('events', 'grid_cols')
    op.drop_column('events', 'grid_rows')
    # ### end Alembic commands ###
