"""add_event_category

Revision ID: 5e0531ce052a
Revises: 49263eb7cb0b
Create Date: 2026-04-26 22:35:10.826079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e0531ce052a'
down_revision: Union[str, None] = '49263eb7cb0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('category', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_column('events', 'category')
    # ### end Alembic commands ###
